server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses/**,/api/lessons/**,/api/units/**

            - id: challenge-service
              uri: lb://challenge-service
              predicates:
                - Path=/api/challenges/**,/api/challengeOptions/**

            - id: progress-service
              uri: lb://progress-service
              predicates:
                - Path=/api/progress/**

            - id: subscription-service
              uri: lb://subscription-service
              predicates:
                - Path=/api/subscriptions/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
