server:
  port: ${CHALLENGE_SERVICE_PORT}

spring:
  application:
    name: challenge-service
  datasource:
    url: jdbc:postgresql://${CHALLENGE_DB_HOST}:${CHALLENGE_DB_PORT}/${CHALLENGE_DB_NAME}?sslmode=require
    username: ${CHALLENGE_DB_USER}
    password: ${CHALLENGE_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    validate-on-migrate: true
#    out-of-order: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

resilience4j:
  retry:
    instances:
      lessonService:
        maxAttempts: 3
        waitDuration: 3s
  circuitbreaker:
    instances:
      lessonService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,env,configprops,loggers,threaddump,
          circuitbreakers,retry,ratelimiters,bulkheads,threadpoolbulkheads,timelimiters
  endpoint:
    health:
      show-details: always