server:
  port: ${CHALLENGE_SERVICE_PORT}

spring:
  application:
    name: challenge-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${CHALLENGE_DB_NAME}
    username: ${CHALLENGE_DB_USER}
    password: ${CHALLENGE_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
