server:
  port: ${PROGRESS_SERVICE_PORT}

spring:
  application:
    name: progress-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${PROGRESS_DB_NAME}
    username: ${PROGRESS_DB_USER}
    password: ${PROGRESS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
