server:
  port: ${SUBSCRIPTION_SERVICE_PORT}

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${SUBSCRIPTION_DB_NAME}
    username: ${SUBSCRIPTION_DB_USER}
    password: ${SUBSCRIPTION_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,env,configprops,loggers,threaddump,
          circuitbreakers,retry,ratelimiters,bulkheads,threadpoolbulkheads,timelimiters
  endpoint:
    health:
      show-details: always